name: Viaduct
options:
  bundleIdPrefix: fr.octostudio.
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.0.0"

schemes:
  Viaduct:
    build:
      targets:
        Viaduct: all
        ViaductTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ViaductTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  Viaduct:
    type: application
    platform: macOS
    sources:
      - Sources/Viaduct
    resources:
      - Sources/Viaduct/Resources/SSHDirectives.json
      - Sources/Viaduct/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: fr.octostudio.Viaduct
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: Sources/Viaduct/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/Viaduct/Resources/Viaduct.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: ""
        ENABLE_PREVIEWS: YES
    dependencies:
      - package: GRDB

  ViaductTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/ViaductTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.qdecosne.ViaductTests
        GENERATE_INFOPLIST_FILE: YES
    scheme:
      testTargets:
        - ViaductTests
    dependencies:
      - target: Viaduct
      - package: GRDB
